root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/main"
cmd = "go build -tags dev -o ./tmp/main cmd/server/main.go"

delay = 20
exclude_dir = ["tmp"]
exclude_file = []
exclude_regex = [".*_templ.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "templ"]
kill_delay = "0s"
log = "build-errors.log"
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false
