application:
  port: 8000
  host: 127.0.0.1
  baseurl: "http://127.0.0.1"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  databasename: "movie-matcher"
  requiressl: false